language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

after_success:
  - cargo build --examples
  - bash coverage.sh

before_deploy:
  - cargo build --release
  - cp target/release/main zeus-compiler
  - tar czvf zeus-compiler-linux.tar.gz zeus-compiler

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - zeus-compiler-linux.tar.gz
  on:
    branch: master
    tags: true
  skip_cleanup: true
